create table quiz_categories
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

alter table quiz_categories
    owner to myuser;

create table pass_quizzes
(
    passid       uuid not null
        primary key,
    createdat    timestamp(6),
    questionlist jsonb,
    quizcategory varchar(255),
    quizid       uuid,
    quizimgurl   varchar(255),
    quizname     varchar(255),
    userid       uuid,
    userlogin    varchar(255),
    username     varchar(255)
);

alter table pass_quizzes
    owner to myuser;

create table quizzes
(
    quizid       uuid not null
        primary key,
    category     varchar(255),
    createdat    timestamp(6),
    imgurl       varchar(255),
    name         varchar(255),
    questionlist jsonb,
    userid       uuid
);

alter table quizzes
    owner to myuser;

create table users
(
    id       uuid not null
        primary key,
    login    varchar(255),
    name     varchar(255),
    password varchar(255),
    role     varchar(255)
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['ADMIN'::character varying, 'USER'::character varying])::text[]))
);

alter table users
    owner to myuser;


